repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      args: ['-l 79']
      language_version: python3.6
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v2.0.0'
  hooks:
    - id: trailing-whitespace
    - id: no-commit-to-branch
    - id: name-tests-test
      args: ['--django']
    - id: flake8
    - id: check-ast
